name:                fomorian
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/Izzimach/fomorian#readme
license:             BSD3
author:              Gary Haussmann
maintainer:          gjhaussmann@gmail.com
copyright:           2018 Gary Haussmann
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - OpenGL >= 3.0 && < 4
  - GLFW-b
  - GLUtil
  - linear
  - filepath
  - hashable
  - vinyl >= 0.8.1
  - vinyl-gl >= 0.3.3
  - ghc-prim
  - lens
  - containers
  - bifunctors
  - mtl

executables:
  fomorian:
    source-dirs:      src
    main:             Main.hs
