name:                fomorian
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/Izzimach/fomorian#readme
license:             BSD3
author:              Gary Haussmann
maintainer:          gjhaussmann@gmail.com
copyright:           2018 Gary Haussmann
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - OpenGL >= 3.0 && < 4
  - GLFW-b
  - GLUtil
  - linear
  - filepath
  - hashable
  - vinyl >= 0.8.1
  - vinyl-gl >= 0.3.3
  - ghc-prim
  - lens
  - containers
  - unordered-containers
  - constraints
  - contravariant
  - bifunctors
  - mtl
  - wavefront
  - vector
  - recursion-schemes
  - text

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints


library:
  source-dirs: src
  exposed-modules:
  - Fomorian.Common
  - Fomorian.SceneNode
  - Fomorian.SceneResources
  - Fomorian.Windowing
  - Fomorian.ProcessWavefront

executables:
  example:
    source-dirs: src
    main:             fomorian/Main.hs
    ghc-options: -threaded -O2
    other-modules:
    - Fomorian.Common
    - Fomorian.SceneNode
    - Fomorian.SceneResources
    - Fomorian.Windowing
    - Fomorian.ProcessWavefront
    - Fomorian.Sample
    dependencies:
    - fomorian

tests:
  spec:
    main: Spec.hs
    source-dirs:
    - test
    dependencies:
    - hspec >= 2.2
    - fomorian

